// frontend-vue/src/views/BooksView.vue
<script setup>
import { ref, reactive, computed, onMounted, inject } from 'vue'
import { BookAPI, CategoryAPI } from '../api.js'
import BookCard from '../components/BookCard.vue'
import BookFormDialog from '../components/BookFormDialog.vue'

const emit = defineEmits(['toast'])
const confirmFn = inject('confirmFn')

const books = ref([])
const categories = ref([])
const loading = ref(false)
const viewMode = ref('grid')
const total = ref(0)

const query = reactive({
  name: '', author: '', publisher: '', categoryId: null,
  page: 1, size: 12
})

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / query.size)))

const dialogVisible = ref(false)
const isEditMode = ref(false)
const dialogRef = ref(null)

async function loadCategories() {
  const res = await CategoryAPI.list()
  if (res.data.code === 200) categories.value = res.data.data || []
}

async function load() {
  loading.value = true
  try {
    const res = await BookAPI.page(query)
    if (res.data.code === 200) {
      const pr = res.data.data || {}
      books.value = pr.records || []
      total.value = pr.total || 0
    } else emit('toast', 'error', res.data.message)
  } catch (e) { emit('toast', 'error', '网络错误') }
  finally { loading.value = false }
}

function search() { query.page = 1; load() }
function resetFilters() {
  query.name = ''; query.author = ''; query.publisher = ''; query.categoryId = null
  query.page = 1
  load()
}
function goPage(p) {
  if (p < 1 || p > totalPages.value) return
  query.page = p
  load()
}

function openAdd() {
  isEditMode.value = false
  if (dialogRef.value) dialogRef.value.reset()
  dialogVisible.value = true
}
function openEdit(book) {
  isEditMode.value = true
  dialogVisible.value = true
  setTimeout(() => { if (dialogRef.value) dialogRef.value.fill(book) }, 50)
}

async function handleSubmit(payload, done) {
  try {
    const res = payload.id != null ? await BookAPI.update(payload) : await BookAPI.add(payload)
    if (res.data.code === 200) {
      emit('toast', 'success', payload.id != null ? '修订完成' : '入藏完成')
      dialogVisible.value = false
      await load()
    } else emit('toast', 'error', res.data.message)
  } catch (e) { emit('toast', 'error', '网络错误') }
  finally { done && done() }
}

async function handleDelete(book) {
  const ok = await confirmFn('移出馆藏', `确定将《${book.name}》移出馆藏?`)
  if (!ok) return
  const res = await BookAPI.remove(book.id)
  if (res.data.code === 200) { emit('toast', 'warning', '已移出'); await load() }
  else emit('toast', 'error', res.data.message)
}

onMounted(async () => { await loadCategories(); await load() })
defineExpose({ reload: load })
</script>

<template>
  <div class="view-header">
    <div>
      <h1 class="view-title">BOOKS<span style="color: var(--yellow)">.</span></h1>
      <p class="view-subtitle">// 馆藏图书 · 共 {{ total }} 条</p>
    </div>
    <div style="display: flex; gap: 12px;">
      <div class="view-toggle">
        <button :class="['toggle-btn', { active: viewMode === 'grid' }]" @click="viewMode = 'grid'">GRID</button>
        <button :class="['toggle-btn', { active: viewMode === 'table' }]" @click="viewMode = 'table'">LIST</button>
      </div>
      <button class="brutalist-btn primary" @click="openAdd">+ 新增</button>
    </div>
  </div>

  <!-- 筛选条 -->
  <div class="filter-bar">
    <div class="filter-group">
      <span class="filter-label">书名</span>
      <input v-model="query.name" class="filter-input" @keyup.enter="search" />
    </div>
    <div class="filter-group">
      <span class="filter-label">作者</span>
      <input v-model="query.author" class="filter-input" @keyup.enter="search" />
    </div>
    <div class="filter-group">
      <span class="filter-label">出版社</span>
      <input v-model="query.publisher" class="filter-input" @keyup.enter="search" />
    </div>
    <div class="filter-group">
      <span class="filter-label">分类</span>
      <select v-model="query.categoryId" class="filter-input">
        <option :value="null">全部</option>
        <option v-for="c in categories" :key="c.id" :value="c.id">{{ c.name }}</option>
      </select>
    </div>
    <button class="brutalist-btn primary" @click="search">GO</button>
    <button class="brutalist-btn" @click="resetFilters">重置</button>
  </div>

  <!-- 内容 -->
  <div v-if="loading" style="padding: 60px; text-align: center;">
    <span class="loading-box" style="font-family: var(--font-display); font-size: 24px;">LOADING...</span>
  </div>
  <div v-else-if="books.length === 0" style="padding: 60px; text-align: center;">
    <p style="font-family: var(--font-display); font-size: 28px;">[ NO DATA ]</p>
    <p style="font-family: var(--font-mono); opacity: 0.6; margin-top: 8px;">无符合条件的图书</p>
  </div>

  <transition-group v-else-if="viewMode === 'grid'" name="grid" tag="div" class="book-grid">
    <BookCard v-for="(b, i) in books" :key="b.id" :book="b" :index="i"
              @edit="openEdit" @delete="handleDelete" />
  </transition-group>

  <div v-else>
    <table class="data-table">
      <thead>
        <tr>
          <th>ID</th><th>书名</th><th>作者</th><th>分类</th>
          <th>定价</th><th>库存</th><th>操作</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="b in books" :key="b.id">
          <td>#{{ String(b.id).padStart(3, '0') }}</td>
          <td style="font-family: var(--font-cn); font-weight: 700;">{{ b.name }}</td>
          <td>{{ b.author || '—' }}</td>
          <td>{{ b.categoryName || '—' }}</td>
          <td>¥{{ Number(b.price || 0).toFixed(2) }}</td>
          <td>{{ b.stock }} / {{ b.totalStock }}</td>
          <td>
            <button class="mini-btn edit" @click="openEdit(b)">编辑</button>
            <button class="mini-btn delete" @click="handleDelete(b)">删除</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- 分页 -->
  <div v-if="!loading && books.length > 0" class="pagination">
    <button class="page-btn" :disabled="query.page <= 1" @click="goPage(query.page - 1)">PREV</button>
    <button v-for="p in totalPages" v-show="Math.abs(p - query.page) < 5 || p === 1 || p === totalPages"
            :key="p" :class="['page-btn', { active: p === query.page }]" @click="goPage(p)">
      {{ p }}
    </button>
    <button class="page-btn" :disabled="query.page >= totalPages" @click="goPage(query.page + 1)">NEXT</button>
    <span class="page-info">{{ query.page }} / {{ totalPages }} · 共 {{ total }} 条</span>
  </div>

  <BookFormDialog ref="dialogRef" :visible="dialogVisible" :is-edit="isEditMode"
                  :categories="categories" @close="dialogVisible = false" @submit="handleSubmit" />
</template>

<style scoped>
.mini-btn {
  font-family: var(--font-mono);
  font-size: 11px;
  letter-spacing: 0.08em;
  padding: 4px 10px;
  border: 1px solid rgba(43, 37, 32, 0.28);
  border-radius: 2px;
  background: var(--white);
  cursor: pointer;
  margin-right: 6px;
  transition: all 0.2s ease;
}
.mini-btn.edit:hover { background: rgba(184, 146, 74, 0.15); color: var(--yellow); border-color: rgba(184, 146, 74, 0.5); }
.mini-btn.delete:hover { background: rgba(139, 58, 58, 0.15); color: var(--pink); border-color: rgba(139, 58, 58, 0.5); }
</style>

// frontend-react/src/views/admin/BooksView.tsx
/**
 * 图书管理
 * - useQuery 分页获取图书(queryKey 含页码与已应用筛选)
 * - useQuery 获取分类列表(下拉选项)
 * - useMutation 新增/更新,useMutation 删除
 */
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useUIStore } from '@/store/uiStore'
import { BookAPI, CategoryAPI } from '@/api'
import type { Book, BookQuery, Category, Page } from '@/types'

/** 分页查询参数(BookQuery 缺 publisher,本地扩展) */
type BookListQuery = BookQuery & { publisher?: string }

/** 图书行(Book 实体含 price/publishDate,但 TS Book 类型缺失,本地扩展) */
type BookRow = Book & { price?: number | string; publishDate?: string }

interface BookFilters {
  name: string
  author: string
  publisher: string
  categoryId: string
}

interface BookForm {
  name: string
  author: string
  publisher: string
  isbn: string
  categoryId: string
  price: string
  stock: string
  publishDate: string
  description: string
}

const emptyFilters: BookFilters = { name: '', author: '', publisher: '', categoryId: '' }

const emptyForm: BookForm = {
  name: '',
  author: '',
  publisher: '',
  isbn: '',
  categoryId: '',
  price: '',
  stock: '',
  publishDate: '',
  description: '',
}

export default function BooksView() {
  const queryClient = useQueryClient()
  const { showToast, confirmFn } = useUIStore()
  const [page, setPage] = useState(1)
  const [size] = useState(10)
  const [filters, setFilters] = useState<BookFilters>(emptyFilters)
  const [applied, setApplied] = useState<BookFilters>(emptyFilters)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState<BookRow | null>(null)
  const [form, setForm] = useState<BookForm>(emptyForm)

  const { data: pageData, isLoading } = useQuery<Page<BookRow>>({
    queryKey: ['books', 'page', page, size, applied],
    queryFn: async () => {
      const params: BookListQuery = {
        page,
        size,
        name: applied.name || undefined,
        author: applied.author || undefined,
        publisher: applied.publisher || undefined,
        categoryId: applied.categoryId || undefined,
      }
      const res = await BookAPI.page(params)
      if (res.ok && res.data) return res.data as Page<BookRow>
      showToast(res.message || '加载失败', 'error')
      return { records: [], total: 0, page, size, pages: 0 }
    },
  })

  const { data: categories = [] } = useQuery<Category[]>({
    queryKey: ['categories'],
    queryFn: async () => {
      const res = await CategoryAPI.list()
      return res.ok ? (res.data ?? []) : []
    },
  })

  const list = pageData?.records ?? []
  const total = pageData?.total ?? 0

  const saveMutation = useMutation({
    mutationFn: (data: Partial<Book>) =>
      editing ? BookAPI.update(data) : BookAPI.add(data),
    onSuccess: (res) => {
      if (res.ok) {
        showToast(editing ? '更新成功' : '新增成功', 'success')
        queryClient.invalidateQueries({ queryKey: ['books', 'page'] })
        setDialogOpen(false)
      } else {
        showToast(res.message || '保存失败', 'error')
      }
    },
  })

  const removeMutation = useMutation({
    mutationFn: (id: number) => BookAPI.remove(id),
    onSuccess: (res) => {
      if (res.ok) {
        showToast('删除成功', 'success')
        queryClient.invalidateQueries({ queryKey: ['books', 'page'] })
      } else {
        showToast(res.message || '删除失败', 'error')
      }
    },
  })

  const onFilter = () => {
    setPage(1)
    setApplied(filters)
  }

  const resetFilter = () => {
    setFilters(emptyFilters)
    setApplied(emptyFilters)
    setPage(1)
  }

  const openAdd = () => {
    setEditing(null)
    setForm(emptyForm)
    setDialogOpen(true)
  }

  const openEdit = (row: BookRow) => {
    setEditing(row)
    setForm({
      name: row.name || '',
      author: row.author || '',
      publisher: row.publisher || '',
      isbn: row.isbn || '',
      categoryId: row.categoryId ? String(row.categoryId) : '',
      price: row.price != null ? String(row.price) : '',
      stock: row.stock != null ? String(row.stock) : '',
      publishDate: row.publishDate ? String(row.publishDate).slice(0, 10) : '',
      description: row.description || '',
    })
    setDialogOpen(true)
  }

  const set = <K extends keyof BookForm>(k: K, v: BookForm[K]) =>
    setForm((p) => ({ ...p, [k]: v }))

  const save = () => {
    if (!form.name || !form.author) {
      showToast('书名和作者必填', 'error')
      return
    }
    const payload: Partial<Book> & {
      price?: number
      publishDate?: string
    } = {
      ...form,
      id: editing?.id,
      categoryId: form.categoryId ? Number(form.categoryId) : undefined,
      price: form.price === '' ? undefined : Number(form.price),
      stock: form.stock === '' ? undefined : Number(form.stock),
      publishDate: form.publishDate || undefined,
    }
    saveMutation.mutate(payload)
  }

  const remove = async (row: BookRow) => {
    const ok = await confirmFn('删除确认', `确定删除《${row.name}》吗？`)
    if (!ok) return
    removeMutation.mutate(row.id)
  }

  const totalPages = Math.max(1, Math.ceil(total / size))
  const catName = (id?: number) => {
    const c = categories.find((x) => x.id === id)
    return c ? c.name : '-'
  }

  return (
    <div>
      <div className="view-header">
        <div>
          <h1 className="view-title">图书管理<span style={{ color: 'var(--terracotta)' }}>.</span></h1>
          <div className="view-subtitle">Books · 馆藏编目与库存</div>
        </div>
        <button className="lib-btn primary" onClick={openAdd}>新增图书</button>
      </div>

      <div className="filter-bar">
        <div className="filter-group">
          <label className="lib-label">书名</label>
          <input
            className="filter-input"
            value={filters.name}
            onChange={(e) => setFilters((p) => ({ ...p, name: e.target.value }))}
            placeholder="按书名搜索"
          />
        </div>
        <div className="filter-group">
          <label className="lib-label">作者</label>
          <input
            className="filter-input"
            value={filters.author}
            onChange={(e) => setFilters((p) => ({ ...p, author: e.target.value }))}
            placeholder="按作者搜索"
          />
        </div>
        <div className="filter-group">
          <label className="lib-label">出版社</label>
          <input
            className="filter-input"
            value={filters.publisher}
            onChange={(e) => setFilters((p) => ({ ...p, publisher: e.target.value }))}
            placeholder="按出版社搜索"
          />
        </div>
        <div className="filter-group">
          <label className="lib-label">分类</label>
          <select
            className="filter-select"
            value={filters.categoryId}
            onChange={(e) => setFilters((p) => ({ ...p, categoryId: e.target.value }))}
          >
            <option value="">全部分类</option>
            {categories.map((c) => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </div>
        <button className="lib-btn primary" onClick={onFilter}>查询</button>
        <button className="lib-btn" onClick={resetFilter}>重置</button>
      </div>

      {isLoading ? (
        <div className="loading-block">加载中...</div>
      ) : list.length === 0 ? (
        <div className="empty-block">暂无数据</div>
      ) : (
        <>
          <div className="record-grid">
            {list.map((b) => (
              <div className="record-card" key={b.id}>
                <div className="record-card-head">
                  <div className="record-card-title">{b.name}</div>
                  <span
                    className={`badge ${
                      (b.stock ?? 0) <= 0
                        ? 'badge-out'
                        : (b.stock ?? 0) <= 3
                        ? 'badge-low'
                        : 'badge-available'
                    }`}
                  >
                    库存 {b.stock ?? 0}
                  </span>
                </div>
                <div className="record-card-meta">
                  <div className="meta-row">
                    <span className="meta-label">作者</span>
                    <span className="meta-value">{b.author || '-'}</span>
                  </div>
                  <div className="meta-row">
                    <span className="meta-label">出版社</span>
                    <span className="meta-value">{b.publisher || '-'}</span>
                  </div>
                  <div className="meta-row">
                    <span className="meta-label">ISBN</span>
                    <span className="meta-value" style={{ fontFamily: 'var(--font-mono)', fontSize: '13px' }}>
                      {b.isbn || '-'}
                    </span>
                  </div>
                  <div className="meta-row">
                    <span className="meta-label">分类</span>
                    <span className="meta-value">{catName(b.categoryId)}</span>
                  </div>
                </div>
                <div className="record-card-foot">
                  <span className="record-card-id">#{b.id}</span>
                  <div className="table-actions">
                    <button className="mini-btn primary" onClick={() => openEdit(b)}>编辑</button>
                    <button className="mini-btn danger" onClick={() => remove(b)}>删除</button>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="pagination">
            <button
              className="page-btn"
              disabled={page <= 1}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
            >
              上一页
            </button>
            <span className="page-info">
              第 {page} / {totalPages} 页 · 共 {total} 条
            </span>
            <button
              className="page-btn"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            >
              下一页
            </button>
          </div>
        </>
      )}

      {dialogOpen && (
        <div className="dialog-mask" onClick={() => setDialogOpen(false)}>
          <div className="dialog-box" onClick={(e) => e.stopPropagation()}>
            <div className="dialog-header">
              <div className="dialog-title">{editing ? '编辑图书' : '新增图书'}</div>
              <button className="dialog-close" onClick={() => setDialogOpen(false)}>×</button>
            </div>
            <div className="dialog-body">
              <div>
                <label className="lib-label">书名 *</label>
                <input className="lib-input" value={form.name}
                  onChange={(e) => set('name', e.target.value)} />
              </div>
              <div>
                <label className="lib-label">作者 *</label>
                <input className="lib-input" value={form.author}
                  onChange={(e) => set('author', e.target.value)} />
              </div>
              <div>
                <label className="lib-label">出版社</label>
                <input className="lib-input" value={form.publisher}
                  onChange={(e) => set('publisher', e.target.value)} />
              </div>
              <div>
                <label className="lib-label">ISBN</label>
                <input className="lib-input" value={form.isbn}
                  onChange={(e) => set('isbn', e.target.value)} />
              </div>
              <div>
                <label className="lib-label">分类</label>
                <select className="filter-select" value={form.categoryId}
                  onChange={(e) => set('categoryId', e.target.value)}>
                  <option value="">请选择分类</option>
                  {categories.map((c) => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div>
                  <label className="lib-label">总价(元)</label>
                  <input className="lib-input" type="number" value={form.price}
                    onChange={(e) => set('price', e.target.value)} />
                </div>
                <div>
                  <label className="lib-label">库存</label>
                  <input className="lib-input" type="number" value={form.stock}
                    onChange={(e) => set('stock', e.target.value)} />
                </div>
              </div>
              <div>
                <label className="lib-label">出版日期</label>
                <input className="lib-input" type="date" value={form.publishDate}
                  onChange={(e) => set('publishDate', e.target.value)} />
              </div>
              <div>
                <label className="lib-label">简介</label>
                <textarea className="lib-input" rows={3} value={form.description}
                  onChange={(e) => set('description', e.target.value)} />
              </div>
            </div>
            <div className="dialog-foot">
              <button className="lib-btn" onClick={() => setDialogOpen(false)}>取消</button>
              <button className="lib-btn primary" disabled={saveMutation.isPending} onClick={save}>
                {saveMutation.isPending ? '保存中...' : '保存'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
