// frontend-react/src/views/admin/DashboardView.tsx
/**
 * 管理员仪表盘
 * - 并行获取 overview + 分类统计 + 热门借阅 + 最近借阅
 * - 指标卡 + 双栏条形图 + 最近借阅表
 * 注意:后端 StatsService 用 jdbcTemplate 返回 Map,key 是 SQL 别名
 */
import { useQuery } from '@tanstack/react-query'
import { useUIStore } from '@/store/uiStore'
import { StatsAPI } from '@/api'

const fmtDate = (d?: string) => (d ? String(d).replace('T', ' ').slice(0, 16) : '-')

/** 后端返回的 Map 原始字段名 */
interface OverviewMap {
  bookCount?: number
  totalStock?: number
  availableStock?: number
  readerCount?: number
  activeBorrows?: number
  overdueCount?: number
  categoryCount?: number
  [k: string]: unknown
}

interface CategoryMap {
  category: string
  count: number
}

interface TopBookMap {
  book: string
  borrow_count: number
}

interface RecentBorrowMap {
  id: number
  book: string
  reader: string
  borrow_date: string
  due_date: string
  status: string
}

interface DashboardData {
  overview: OverviewMap
  categories: CategoryMap[]
  topBorrowed: TopBookMap[]
  recent: RecentBorrowMap[]
}

type BorrowStatus = 'BORROWED' | 'RETURNED' | 'OVERDUE'

export default function DashboardView() {
  const { showToast } = useUIStore()

  const { data, isLoading, refetch } = useQuery<DashboardData>({
    queryKey: ['admin-dashboard'],
    queryFn: async () => {
      const [o, c, t, r] = await Promise.all([
        StatsAPI.overview(),
        StatsAPI.booksPerCategory(),
        StatsAPI.topBorrowed(5),
        StatsAPI.recentBorrows(10),
      ])
      if (!o.ok || !c.ok || !t.ok || !r.ok) showToast('部分数据加载失败', 'error')
      return {
        overview: (o.data ?? {}) as unknown as OverviewMap,
        categories: (c.data ?? []) as unknown as CategoryMap[],
        topBorrowed: (t.data ?? []) as unknown as TopBookMap[],
        recent: (r.data ?? []) as unknown as RecentBorrowMap[],
      }
    },
  })

  const overview = data?.overview ?? {}
  const categories = data?.categories ?? []
  const topBorrowed = data?.topBorrowed ?? []
  const recent = data?.recent ?? []

  const totalBooks = overview.bookCount || 0
  const totalReaders = overview.readerCount || 0
  const totalStock = overview.totalStock || 0
  const activeBorrows = overview.activeBorrows || 0
  const overdueCount = overview.overdueCount || 0

  const maxCat = Math.max(1, ...categories.map((c) => c.count || 0))
  const maxTop = Math.max(1, ...topBorrowed.map((t) => t.borrow_count || 0))

  const statusBadge = (status: string) => {
    const map: Record<string, string> = {
      BORROWED: 'badge-borrowed',
      RETURNED: 'badge-returned',
      OVERDUE: 'badge-overdue',
    }
    return map[status] || 'badge-pending'
  }
  const statusText = (status: string) => {
    const map: Record<string, string> = {
      BORROWED: '借阅中',
      RETURNED: '已归还',
      OVERDUE: '已逾期',
    }
    return map[status] || status || '-'
  }

  return (
    <div>
      <div className="view-header">
        <div>
          <h1 className="view-title">仪表盘<span style={{ color: 'var(--terracotta)' }}>.</span></h1>
          <div className="view-subtitle">Dashboard · 馆藏与借阅概览</div>
        </div>
        <button className="lib-btn primary" onClick={() => refetch()}>刷新</button>
      </div>

      {isLoading ? (
        <div className="loading-block">加载中...</div>
      ) : (
        <>
          {/* 指标卡 */}
          <div className="dashboard-grid">
            <div className="metric-card yellow">
              <div className="metric-num">{totalBooks}</div>
              <div className="metric-label">馆藏种类</div>
            </div>
            <div className="metric-card blue">
              <div className="metric-num">{totalStock}</div>
              <div className="metric-label">馆藏总量</div>
            </div>
            <div className="metric-card green">
              <div className="metric-num">{totalReaders}</div>
              <div className="metric-label">读者总数</div>
            </div>
            <div className="metric-card orange">
              <div className="metric-num">{activeBorrows}</div>
              <div className="metric-label">在借数量</div>
            </div>
            <div className="metric-card pink">
              <div className="metric-num">{overdueCount}</div>
              <div className="metric-label">逾期数量</div>
            </div>
          </div>

          {/* 双栏:分类图书条形图 + 热门借阅 Top5 */}
          <div className="split-panel" style={{ marginTop: '20px' }}>
            <div className="bar-chart">
              <div className="bar-row" style={{ gridTemplateColumns: '1fr', marginBottom: '8px' }}>
                <span className="bar-label" style={{ fontSize: '14px', fontWeight: 700 }}>
                  分类图书分布
                </span>
              </div>
              {categories.length === 0 ? (
                <div className="empty-block">暂无数据</div>
              ) : (
                categories.map((c, i) => (
                  <div className="bar-row" key={i}>
                    <span className="bar-label">{c.category}</span>
                    <div className="bar-track">
                      <div
                        className="bar-fill"
                        style={{ width: `${((c.count || 0) / maxCat) * 100}%` }}
                      ></div>
                    </div>
                    <span className="bar-value">{c.count || 0}</span>
                  </div>
                ))
              )}
            </div>

            <div className="bar-chart">
              <div className="bar-row" style={{ gridTemplateColumns: '1fr', marginBottom: '8px' }}>
                <span className="bar-label" style={{ fontSize: '14px', fontWeight: 700 }}>
                  热门借阅 Top 5
                </span>
              </div>
              {topBorrowed.length === 0 ? (
                <div className="empty-block">暂无数据</div>
              ) : (
                topBorrowed.map((t, i) => (
                  <div className="bar-row" key={i}>
                    <span className="bar-label">{t.book}</span>
                    <div className="bar-track">
                      <div
                        className="bar-fill"
                        style={{ width: `${((t.borrow_count || 0) / maxTop) * 100}%` }}
                      ></div>
                    </div>
                    <span className="bar-value">{t.borrow_count || 0}</span>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* 最近借阅 */}
          <div style={{ marginTop: '24px' }}>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '20px', marginBottom: '12px' }}>
              最近借阅记录
            </h2>
            {recent.length === 0 ? (
              <div className="empty-block">暂无数据</div>
            ) : (
              <div className="record-grid">
                {recent.map((r, i) => (
                  <div className="record-card" key={i}>
                    <div className="record-card-head">
                      <div className="record-card-title">{r.book || '-'}</div>
                      <span className={`badge ${statusBadge(r.status)}`}>
                        {statusText(r.status)}
                      </span>
                    </div>
                    <div className="record-card-meta">
                      <div className="meta-row">
                        <span className="meta-label">读者</span>
                        <span className="meta-value">{r.reader || '-'}</span>
                      </div>
                      <div className="meta-row">
                        <span className="meta-label">借出日期</span>
                        <span className="meta-value" style={{ fontFamily: 'var(--font-mono)', fontSize: '13px' }}>
                          {fmtDate(r.borrow_date)}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  )
}

// frontend-vue/src/views/DashboardView.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { StatsAPI } from '../api.js'

const emit = defineEmits(['toast'])

const overview = ref({})
const categoryData = ref([])
const topBooks = ref([])
const recentList = ref([])
const loading = ref(true)

const maxCategoryCount = computed(() =>
  Math.max(1, ...categoryData.value.map(c => Number(c.count || 0)))
)

const maxBorrowCount = computed(() =>
  Math.max(1, ...topBooks.value.map(b => Number(b.borrow_count || 0)))
)

function statusBadge(status) {
  return {
    BORROWED: 'badge-borrowed',
    RETURNED: 'badge-returned',
    OVERDUE: 'badge-overdue'
  }[status] || 'badge-borrowed'
}

async function loadAll() {
  loading.value = true
  try {
    const [ov, cat, top, recent] = await Promise.all([
      StatsAPI.overview(),
      StatsAPI.booksPerCategory(),
      StatsAPI.topBorrowed(5),
      StatsAPI.recentBorrows(8)
    ])
    overview.value = ov.data.data || {}
    categoryData.value = cat.data.data || []
    topBooks.value = top.data.data || []
    recentList.value = recent.data.data || []
  } catch (e) {
    emit('toast', 'error', '仪表盘数据加载失败')
    console.error(e)
  } finally {
    loading.value = false
  }
}

onMounted(loadAll)
defineExpose({ reload: loadAll })
</script>

<template>
  <div class="view-header">
    <div>
      <h1 class="view-title">DASHBOARD<span style="color: var(--yellow)">.</span></h1>
      <p class="view-subtitle">// 实时馆藏运营快照</p>
    </div>
    <button class="brutalist-btn primary" @click="loadAll">↻ 刷新</button>
  </div>

  <div v-if="loading" class="loading-state" style="padding: 60px; text-align: center;">
    <span class="loading-box" style="font-family: var(--font-display); font-size: 24px;">LOADING...</span>
  </div>

  <template v-else>
    <!-- 指标卡 -->
    <div class="dashboard-grid">
      <div class="metric-card pink">
        <div class="metric-label">藏书种类</div>
        <div class="metric-num">{{ overview.bookCount || 0 }}</div>
      </div>
      <div class="metric-card yellow">
        <div class="metric-label">总馆藏</div>
        <div class="metric-num">{{ overview.totalStock || 0 }}</div>
      </div>
      <div class="metric-card green">
        <div class="metric-label">可借</div>
        <div class="metric-num">{{ overview.availableStock || 0 }}</div>
      </div>
      <div class="metric-card blue">
        <div class="metric-label">读者</div>
        <div class="metric-num">{{ overview.readerCount || 0 }}</div>
      </div>
      <div class="metric-card orange">
        <div class="metric-label">借出中</div>
        <div class="metric-num">{{ overview.activeBorrows || 0 }}</div>
      </div>
      <div class="metric-card pink">
        <div class="metric-label">逾期</div>
        <div class="metric-num">{{ overview.overdueCount || 0 }}</div>
      </div>
    </div>

    <!-- 图表区 -->
    <div class="split-panel">
      <div>
        <h2 class="view-title" style="font-size: 24px; margin-bottom: 12px;">分类分布</h2>
        <div class="bar-chart">
          <div v-for="c in categoryData" :key="c.category" class="bar-row">
            <span class="bar-label">{{ c.category }}</span>
            <div class="bar-track">
              <div class="bar-fill"
                   :style="{ width: ((Number(c.count || 0) / maxCategoryCount) * 100) + '%', background: 'rgba(139, 58, 58, 0.75)' }">
              </div>
            </div>
            <span class="bar-value">{{ c.count || 0 }}</span>
          </div>
        </div>
      </div>

      <div>
        <h2 class="view-title" style="font-size: 24px; margin-bottom: 12px;">借阅 TOP5</h2>
        <div class="bar-chart">
          <div v-for="b in topBooks" :key="b.book" class="bar-row">
            <span class="bar-label" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ b.book }}</span>
            <div class="bar-track">
              <div class="bar-fill"
                   :style="{ width: ((Number(b.borrow_count || 0) / maxBorrowCount) * 100) + '%', background: 'rgba(184, 146, 74, 0.75)' }">
              </div>
            </div>
            <span class="bar-value">{{ b.borrow_count || 0 }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- 最近借阅 -->
    <div style="margin-top: 32px;">
      <h2 class="view-title" style="font-size: 24px; margin-bottom: 12px;">最近借阅</h2>
      <table class="data-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>图书</th>
            <th>读者</th>
            <th>借出日</th>
            <th>应还日</th>
            <th>状态</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in recentList" :key="r.id">
            <td>#{{ String(r.id).padStart(3, '0') }}</td>
            <td style="font-family: var(--font-cn); font-weight: 700;">{{ r.book }}</td>
            <td>{{ r.reader }}</td>
            <td>{{ r.borrow_date }}</td>
            <td>{{ r.due_date }}</td>
            <td><span :class="['badge', statusBadge(r.status)]">{{ r.status }}</span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>
</template>
