// frontend-react/src/views/reader/MyReviewsView.tsx
/**
 * 我的评价
 * - useQuery 获取我发表的评价列表
 * - useMutation 删除评价,成功后失效列表查询
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useUIStore } from '@/store/uiStore'
import { ReviewAPI } from '@/api'
import type { Review } from '@/types'

const fmtDate = (d?: string) => (d ? String(d).replace('T', ' ').slice(0, 16) : '-')
const renderStars = (rating: number) => (
  <span className="stars">
    {[1, 2, 3, 4, 5].map((i) => (
      <span key={i} className={`star ${i > rating ? 'empty' : ''}`.trim()}>
        ★
      </span>
    ))}
  </span>
)

export default function MyReviewsView() {
  const queryClient = useQueryClient()
  const { showToast, confirmFn } = useUIStore()

  const { data: list = [], isLoading, refetch } = useQuery<Review[]>({
    queryKey: ['my-reviews'],
    queryFn: async () => {
      const res = await ReviewAPI.my()
      if (res.ok) return res.data ?? []
      showToast(res.message || '加载失败', 'error')
      return []
    },
  })

  const removeMutation = useMutation({
    mutationFn: (id: number) => ReviewAPI.remove(id),
    onSuccess: async (res) => {
      if (res.ok) {
        showToast('已删除评价', 'success')
        await queryClient.invalidateQueries({ queryKey: ['my-reviews'] })
      } else {
        showToast(res.message || '删除失败', 'error')
      }
    },
  })

  const remove = async (row: Review) => {
    const ok = await confirmFn('删除评价', `确定删除对《${row.bookName}》的评价吗?`)
    if (!ok) return
    removeMutation.mutate(row.id)
  }

  return (
    <div>
      <div className="view-header">
        <div>
          <h1 className="view-title">
            我的评价<span style={{ color: 'var(--terracotta)' }}>.</span>
          </h1>
          <div className="view-subtitle">My Reviews · 我发表过的图书评价</div>
        </div>
        <button className="lib-btn primary" onClick={() => refetch()}>刷新</button>
      </div>

      {isLoading ? (
        <div className="loading-block">加载中...</div>
      ) : list.length === 0 ? (
        <div className="empty-block">暂未发表评价,前往浏览馆藏分享你的看法</div>
      ) : (
        <div>
          {list.map((r) => (
            <div className="list-card" key={r.id}>
              <div className="list-card-head">
                <div className="list-card-title">{r.bookName || '-'}</div>
                {renderStars(r.rating || 0)}
              </div>
              <div className="list-card-body">{r.content || '-'}</div>
              <div className="list-card-foot">
                <span className="meta-row">
                  <span className="meta-label">发表时间</span>
                  <span className="meta-value mono">{fmtDate(r.createTime)}</span>
                </span>
                <button
                  className="mini-btn danger"
                  disabled={removeMutation.isPending}
                  onClick={() => remove(r)}
                >
                  删除
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// frontend-vue/src/views/MyReviewsView.vue
<script setup>
import { ref, onMounted, inject } from 'vue'
import { ReviewAPI } from '../api.js'
import { showToast } from '../composables/useToast.js'
const confirmFn = inject('confirmFn')

const list = ref([])
const loading = ref(false)

async function load() {
  loading.value = true
  try {
    const res = await ReviewAPI.my()
    if (res.data.code === 200) list.value = res.data.data || []
    else showToast('error', '加载失败')
  } catch (e) { showToast('error', '加载失败') }
  finally { loading.value = false }
}

async function remove(rv) {
  const ok = await confirmFn('删除评价', `确定删除对《${rv.bookName}》的评价?`)
  if (!ok) return
  const res = await ReviewAPI.remove(rv.id)
  if (res.data.code === 200) {
    showToast('success', '已删除')
    await load()
  } else showToast('error', res.data.message)
}

function stars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n)
}

onMounted(load)
defineExpose({ reload: load })
</script>

<template>
  <div class="view-header">
    <div>
      <h1 class="view-title">MY REVIEWS<span style="color: var(--yellow)">.</span></h1>
      <p class="view-subtitle">// 我的图书评价 · 共 {{ list.length }} 条</p>
    </div>
    <button class="brutalist-btn" @click="load">刷新</button>
  </div>

  <div v-if="loading" class="loading-block"><span>LOADING...</span></div>

  <div v-else-if="list.length === 0" class="empty-block">
    <span>// 暂无评价</span>
    <p style="margin-top: 12px; opacity: 0.6;">前往「Browse」浏览图书并对已借阅的书发表评价</p>
  </div>

  <div v-else class="review-list">
    <article v-for="rv in list" :key="rv.id" class="review-card">
      <div class="review-head">
        <div class="head-left">
          <h3 class="review-book">{{ rv.bookName }}</h3>
          <span class="review-stars">{{ stars(rv.rating) }}</span>
        </div>
        <span class="review-date mono">{{ (rv.createTime || '').replace('T', ' ').slice(0, 16) }}</span>
      </div>
      <p v-if="rv.content" class="review-content">{{ rv.content }}</p>
      <p v-else class="review-content" style="opacity:0.4;">// 未填写评价内容</p>
      <div class="review-foot">
        <span class="rating-num">{{ rv.rating }} / 5</span>
        <button class="mini-btn danger" @click="remove(rv)">删除</button>
      </div>
    </article>
  </div>
</template>

<style scoped>
.loading-block, .empty-block {
  padding: 60px; text-align: center;
  background: var(--card); border: 1px solid var(--border);
  box-shadow: var(--shadow-sm);
  font-family: var(--font-sans); font-size: 13px;
  color: var(--muted);
  border-radius: var(--radius);
}
.review-list { display: flex; flex-direction: column; gap: 12px; }
.review-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow-sm);
  padding: 16px 20px;
  border-left: 3px solid var(--primary);
  transition: box-shadow 0.16s ease;
}
.review-card:hover { box-shadow: var(--shadow-md); }
.review-head {
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 8px; gap: 12px;
}
.head-left { display: flex; gap: 12px; align-items: baseline; flex-wrap: wrap; }
.review-book {
  font-family: var(--font-sans); font-size: 18px; font-weight: 700;
  color: var(--foreground);
}
.review-stars { color: var(--primary); font-size: 16px; letter-spacing: 2px; }
.review-date { font-size: 11px; color: var(--muted); }
.review-content {
  font-family: var(--font-sans); font-size: 14px;
  line-height: 1.7; color: var(--foreground-secondary);
  padding: 8px 0;
}
.review-foot {
  display: flex; justify-content: space-between; align-items: center;
  padding-top: 8px; border-top: 1px solid var(--border-faint);
}
.rating-num {
  font-family: var(--font-display); font-size: 16px;
  color: var(--foreground);
}
.mini-btn {
  font-family: var(--font-sans); font-size: 12px; font-weight: 500;
  padding: 6px 14px; background: var(--card);
  border: 1px solid var(--border); border-radius: var(--radius-sm);
  cursor: pointer;
  transition: all 0.16s ease;
}
.mini-btn.danger { background: #fcdede; color: var(--destructive); border-color: rgba(239,68,68,0.4); }
.mini-btn.danger:hover { background: var(--destructive); color: white; border-color: var(--destructive); }
</style>
